version: '3'

services:
    db:
        image: mysql:8.0
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - net
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        env_file:
            - .env
        volumes:
            - ./app/:/var/www/symfony/
        networks:
            - net
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/symfony/
        ports:
            - 8001:80
        networks:
            - net
    redis:
        image: redis:alpine
        ports:
            - 6379
        networks:
            - net
    rabbitmq:
        image: rabbitmq:management
        ports:
            - 5672
            - 15672:15672
        networks:
            - net

networks:
    net:
